server:
  port: 8700
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          # 这里填写的是本地仓库地址，远程仓库直接填写远程仓库地址 http://git...
          uri: https://github.com/d0ng-18/config-repo.git
          # 默认分支设定为你自己本地或是远程分支的名称
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka, http://localhost:8002/eureka